### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by AlexRockstroh** [AlexRockstroh/projectMultimodal#2]
- Wir müssen später noch implementieren, dass das Backend eine Fehlermeldung zurückgibt ,wenn versucht wird über Alexa ein Stein in eine Reihe zu setzen, welche bereits voll ist. Vorher hatten wir das im Frontend der App abgefangen, was bei Sprachbedienung ja wegfällt

**Comment by AlexRockstroh** [comment]
- Wenn man mit Alexa die App starten will (also den 1. Button drücken möchte, wenn die Anwendung startet), sollten wir abfangen, dass danach der Button nicht mehr getriggert wird

**Comment by AlexRockstroh** [comment]
- JavaFX Pfade bzw libary sind aktuell vom Nutzer abhängig... Vielleicht für die Abgabe das Ganze statisch einbinden?

**Comment by AlexRockstroh** [comment]
- gitIgnore kommt mit der neuen Ordnerstruktur nicht klar

**Comment by FoxBanri** [comment]
disable buttons in desktop app implementieren. Steht zwar schon im code aber der onAction im fxml kommt dem ganzen in die quere

**Comment by AlexRockstroh** [comment]
Hello world krams noch entfernen

**Comment by AlexRockstroh** [comment]
Neustart-button etwas verschoben

**Comment by AlexRockstroh** [comment]
Alexa Start-Befehl wird falsch verarbeitet wenn bereits die app läuft

**Comment by AlexRockstroh** [comment]
surface für präsentation vorbereiten

**Comment by AlexRockstroh** [comment]
andere farbe für siegertext, liest sich nicht so gut auf hellen hintergrund

**Comment by AlexRockstroh** [comment]
Gullasch-Dokument schreiben und Abgabe vorbereiten
